-- Hybrid open + internal feature views for forecast models.
-- These views avoid direct patient identifiers and join public context at site-hour/day grain.

CREATE SCHEMA IF NOT EXISTS MODELS;

CREATE OR REPLACE VIEW MODELS.V_SITE_HOUR_ARRIVAL_FEATURES AS
SELECT
  v.INSTITUTION_NAME,
  v.INSTITUTION_ZONE_NAME,
  DATE_TRUNC('hour', v.FIRST_CONTACT_DATETIME) AS SITE_HOUR,
  HOUR(v.FIRST_CONTACT_DATETIME) AS ARRIVAL_HOUR,
  DAYOFWEEK(v.FIRST_CONTACT_DATETIME) AS ARRIVAL_DAY_OF_WEEK,
  COUNT(*) AS ARRIVALS,
  SUM(IFF(v.PATIENT_AGE_GROUP IN ('Newborn','Neonate','Paediatric'), 1, 0)) AS PEDIATRIC_ARRIVALS,
  AVG(IFF(v.DISPOSITION_PERFORMANCE_REPORT = 'Admitted', 1, 0)) AS ADMISSION_RATE,
  AVG(IFF(v.DISPOSITION_PERFORMANCE_REPORT = 'LWBS', 1, 0)) AS LWBS_RATE,
  APPROX_PERCENTILE(v.ED_LOS_HRS, 0.50) AS ED_LOS_P50_HRS,
  APPROX_PERCENTILE(v.ED_LOS_HRS, 0.90) AS ED_LOS_P90_HRS,
  APPROX_PERCENTILE(v.ED_LOS_FIRST_CONTACT_TO_PHYSICIAN_INITIAL_ASSESSMENT_HRS, 0.50) AS PIA_P50_HRS,
  APPROX_PERCENTILE(v.ED_LOS_FIRST_CONTACT_TO_PHYSICIAN_INITIAL_ASSESSMENT_HRS, 0.90) AS PIA_P90_HRS,
  AVG(e.ENVIRONMENTAL_STRESS_INDEX) AS ENVIRONMENTAL_STRESS_INDEX,
  AVG(e.AQHI) AS AQHI,
  AVG(e.WILDFIRE_SMOKE_RISK) AS WILDFIRE_SMOKE_RISK,
  AVG(t.TRAVEL_FRICTION_INDEX) AS TRAVEL_FRICTION_INDEX,
  AVG(r.PEDIATRIC_PRESSURE_INDEX) AS PEDIATRIC_RESPIRATORY_PRESSURE,
  AVG(w.ESTIMATED_WAIT_MINS) AS PUBLIC_WAIT_MINS
FROM CURATED.V_ED_VISITS_CORE v
LEFT JOIN OPEN_DATA.ENVIRONMENTAL_STRESS e
  ON e.FACILITY = v.INSTITUTION_NAME
 AND DATE_TRUNC('hour', e.OBSERVED_AT) = DATE_TRUNC('hour', v.FIRST_CONTACT_DATETIME)
LEFT JOIN OPEN_DATA.TRAVEL_FRICTION t
  ON t.FACILITY = v.INSTITUTION_NAME
 AND DATE_TRUNC('hour', t.OBSERVED_AT) = DATE_TRUNC('hour', v.FIRST_CONTACT_DATETIME)
LEFT JOIN OPEN_DATA.AB_RESPIRATORY_SURVEILLANCE r
  ON r.ZONE = v.INSTITUTION_ZONE_NAME
 AND r.WEEK_START = DATE_TRUNC('week', v.FIRST_CONTACT_DATETIME)
LEFT JOIN OPEN_DATA.AHS_ED_WAIT_TIMES w
  ON w.FACILITY = v.INSTITUTION_NAME
 AND DATE_TRUNC('hour', w.POSTED_TIMESTAMP) = DATE_TRUNC('hour', v.FIRST_CONTACT_DATETIME)
GROUP BY 1,2,3,4,5;

CREATE OR REPLACE VIEW MODELS.V_SITE_DAY_ARRIVAL_FEATURES AS
SELECT
  INSTITUTION_NAME,
  INSTITUTION_ZONE_NAME,
  CAST(SITE_HOUR AS DATE) AS SITE_DATE,
  SUM(ARRIVALS) AS ARRIVALS,
  SUM(PEDIATRIC_ARRIVALS) AS PEDIATRIC_ARRIVALS,
  AVG(ADMISSION_RATE) AS ADMISSION_RATE,
  AVG(LWBS_RATE) AS LWBS_RATE,
  AVG(ED_LOS_P50_HRS) AS ED_LOS_P50_HRS,
  MAX(ED_LOS_P90_HRS) AS ED_LOS_P90_HRS,
  AVG(ENVIRONMENTAL_STRESS_INDEX) AS ENVIRONMENTAL_STRESS_INDEX,
  AVG(TRAVEL_FRICTION_INDEX) AS TRAVEL_FRICTION_INDEX,
  AVG(PEDIATRIC_RESPIRATORY_PRESSURE) AS PEDIATRIC_RESPIRATORY_PRESSURE,
  AVG(PUBLIC_WAIT_MINS) AS PUBLIC_WAIT_MINS
FROM MODELS.V_SITE_HOUR_ARRIVAL_FEATURES
GROUP BY 1,2,3;
