-- Lineage, model registry, and audit tables for Action Intelligence.

CREATE SCHEMA IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS MODELS;
CREATE SCHEMA IF NOT EXISTS APP_CONFIG;

CREATE TABLE IF NOT EXISTS GOVERNANCE.DATA_LINEAGE_MANIFEST (
  ARTIFACT_NAME STRING NOT NULL,
  SOURCE_ID STRING NOT NULL,
  SOURCE_CATEGORY STRING NOT NULL,
  SOURCE_GRAIN STRING,
  SOURCE_GEOGRAPHY STRING,
  GENERATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  SYNTHETIC_FLAG BOOLEAN NOT NULL,
  CAVEAT STRING
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.ACTION_INTELLIGENCE_AUDIT_LOG (
  AUDIT_ID STRING DEFAULT UUID_STRING(),
  EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  APP_SURFACE STRING NOT NULL,
  USER_ROLE STRING,
  FACILITY STRING,
  ACTION_TYPE STRING,
  SCENARIO_NAME STRING,
  MODEL_VERSION STRING,
  DATA_FRESHNESS_SUMMARY VARIANT,
  HUMAN_DECISION_REQUIRED BOOLEAN DEFAULT TRUE,
  NOTES STRING
);

CREATE TABLE IF NOT EXISTS MODELS.MODEL_REGISTRY (
  MODEL_NAME STRING NOT NULL,
  TARGET_NAME STRING NOT NULL,
  MODEL_FAMILY STRING NOT NULL,
  FEATURE_LIST VARIANT,
  TRAINING_WINDOW STRING,
  VALIDATION_WINDOW STRING,
  METRICS VARIANT,
  LIMITATIONS STRING,
  APPROVED_FOR_OPERATIONAL_USE BOOLEAN DEFAULT FALSE,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_CONFIG.ACTION_INTELLIGENCE_SETTINGS (
  SETTING_NAME STRING NOT NULL,
  SETTING_VALUE VARIANT,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY_ROLE STRING
);
