-- Lineage, refresh, audit, and model-use controls.

CREATE SCHEMA IF NOT EXISTS GOVERNANCE;

CREATE TABLE IF NOT EXISTS OPEN_DATA.REFRESH_AUDIT_LOG (
    SOURCE_ID STRING,
    REFRESHED_AT TIMESTAMP_NTZ,
    STATUS STRING,
    MESSAGE STRING
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.DATA_SOURCE_REGISTRY (
    SOURCE_ID STRING,
    DISPLAY_NAME STRING,
    SOURCE_FAMILY STRING,
    CATEGORY STRING,
    OFFICIAL_URL STRING,
    OWNER STRING,
    EXPECTED_REFRESH_MINUTES NUMBER,
    SNOWFLAKE_TARGET STRING,
    PII_RISK STRING,
    NOTES STRING,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.SCENARIO_AUDIT_LOG (
    SCENARIO_ID STRING,
    USER_ROLE STRING,
    CREATED_AT TIMESTAMP_NTZ,
    FACILITY STRING,
    INPUT_JSON VARIANT,
    DATA_VERSION_JSON VARIANT,
    RANDOM_SEED NUMBER,
    OUTPUT_SUMMARY_JSON VARIANT,
    MODEL_PROVIDER STRING,
    HUMAN_REVIEW_REQUIRED BOOLEAN
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.MODEL_CALL_AUDIT_LOG (
    CALL_ID STRING,
    CREATED_AT TIMESTAMP_NTZ,
    MODEL_PROVIDER STRING,
    USE_CASE STRING,
    INPUT_DATA_CLASS STRING,
    OUTPUT_DATA_CLASS STRING,
    APPROVAL_REFERENCE STRING,
    STATUS STRING
);
