-- Open/public data landing schema for ED Flow Intelligence v2.
-- Local prototype uses synthetic CSV fallbacks; these tables are Snowflake-ready targets.

CREATE SCHEMA IF NOT EXISTS OPEN_DATA;

CREATE TABLE IF NOT EXISTS OPEN_DATA.AHS_ED_WAIT_TIMES (
    FACILITY STRING,
    ZONE STRING,
    CITY STRING,
    POSTED_TIMESTAMP TIMESTAMP_NTZ,
    ESTIMATED_WAIT_MINS NUMBER,
    SITE_OPEN BOOLEAN,
    PUBLIC_MESSAGE STRING,
    SOURCE_CATEGORY STRING,
    OFFICIAL_SOURCE STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPEN_DATA.AB_RESPIRATORY_SURVEILLANCE (
    ZONE STRING,
    WEEK_START DATE,
    PATHOGEN STRING,
    TEST_POSITIVITY FLOAT,
    NEW_HOSPITAL_ADMISSIONS NUMBER,
    PEDIATRIC_PRESSURE_INDEX FLOAT,
    SCHOOL_ABSENTEEISM_PROXY FLOAT,
    SOURCE_CATEGORY STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPEN_DATA.ENVIRONMENTAL_STRESS (
    FACILITY STRING,
    ZONE STRING,
    CITY STRING,
    OBSERVED_AT TIMESTAMP_NTZ,
    TEMPERATURE_C FLOAT,
    HUMIDEX FLOAT,
    AQHI NUMBER,
    WILDFIRE_SMOKE_RISK FLOAT,
    WEATHER_ALERT_COUNT NUMBER,
    HEAT_ALERT BOOLEAN,
    ENVIRONMENTAL_STRESS_INDEX FLOAT,
    SOURCE_CATEGORY STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPEN_DATA.TRAVEL_FRICTION (
    FACILITY STRING,
    ZONE STRING,
    CITY STRING,
    OBSERVED_AT TIMESTAMP_NTZ,
    ROAD_INCIDENTS NUMBER,
    ROAD_CLOSURES NUMBER,
    TRANSIT_DISRUPTION_INDEX FLOAT,
    MAJOR_EVENT_INDEX FLOAT,
    TRAVEL_FRICTION_INDEX FLOAT,
    SOURCE_CATEGORY STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPEN_DATA.CALENDAR_CONTEXT (
    CALENDAR_DATE DATE,
    CALENDAR_LABEL STRING,
    CALENDAR_TYPE STRING,
    SCHOOL_IN_SESSION BOOLEAN,
    SOURCE_CATEGORY STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
