-- Streams, tasks, and refresh log pattern for Snowflake open-data ingestion.
-- Public URLs and credentials must be configured through approved integrations.

CREATE SCHEMA IF NOT EXISTS OPEN_DATA;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE;

CREATE TABLE IF NOT EXISTS GOVERNANCE.OPEN_DATA_REFRESH_LOG (
  SOURCE_ID STRING NOT NULL,
  REFRESH_STARTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  REFRESH_COMPLETED_AT TIMESTAMP_NTZ,
  STATUS STRING NOT NULL,
  ROW_COUNT NUMBER,
  MAX_SOURCE_TIMESTAMP TIMESTAMP_NTZ,
  QUALITY_SCORE FLOAT,
  FALLBACK_USED BOOLEAN DEFAULT FALSE,
  MESSAGE STRING
);

CREATE TABLE IF NOT EXISTS OPEN_DATA.SOURCE_REGISTRY (
  SOURCE_ID STRING NOT NULL,
  DISPLAY_NAME STRING NOT NULL,
  SOURCE_FAMILY STRING,
  CATEGORY STRING,
  EXPECTED_REFRESH_MINUTES NUMBER,
  GRAIN STRING,
  GEOGRAPHY STRING,
  SNOWFLAKE_TARGET STRING,
  ACTIVATION_STATUS STRING,
  BLOCKING_ISSUE STRING,
  PUBLIC_SAFE BOOLEAN DEFAULT TRUE
);

CREATE STREAM IF NOT EXISTS OPEN_DATA.SOURCE_REGISTRY_CHANGES
ON TABLE OPEN_DATA.SOURCE_REGISTRY;

CREATE OR REPLACE VIEW GOVERNANCE.V_OPEN_DATA_LATEST_REFRESH AS
SELECT *
FROM GOVERNANCE.OPEN_DATA_REFRESH_LOG
QUALIFY ROW_NUMBER() OVER (PARTITION BY SOURCE_ID ORDER BY REFRESH_STARTED_AT DESC) = 1;
