-- Expected secure internal operational feeds.
-- These are placeholder schemas for governed design review, not local external data.

CREATE SCHEMA IF NOT EXISTS OPERATIONS;

CREATE TABLE IF NOT EXISTS OPERATIONS.REAL_TIME_ED_LOCATION_EVENTS (
    EVENT_ID STRING,
    VISIT_KEY STRING,
    FACILITY STRING,
    EVENT_TYPE STRING,
    EVENT_DTTM TIMESTAMP_NTZ,
    LOCATION_ID STRING,
    LOCATION_DESCRIPTION STRING,
    SOURCE_SYSTEM STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPERATIONS.ADT_BED_BOARD_STATUS (
    SNAPSHOT_DTTM TIMESTAMP_NTZ,
    FACILITY STRING,
    UNIT_ID STRING,
    UNIT_NAME STRING,
    BED_ID_HASH STRING,
    BED_STATUS STRING,
    ISOLATION_COMPATIBILITY STRING,
    SERVICE_LINE STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPERATIONS.STAFFING_ROSTERS (
    SHIFT_START_DTTM TIMESTAMP_NTZ,
    SHIFT_END_DTTM TIMESTAMP_NTZ,
    FACILITY STRING,
    STAFF_GROUP STRING,
    ROLE_GROUP STRING,
    COUNT_ON_SHIFT NUMBER,
    SOURCE_SYSTEM STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPERATIONS.CONSULT_QUEUES (
    SNAPSHOT_DTTM TIMESTAMP_NTZ,
    FACILITY STRING,
    SERVICE_LINE STRING,
    REQUESTS_WAITING NUMBER,
    MEDIAN_AGE_MINS NUMBER,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPERATIONS.DIAGNOSTIC_TURNAROUND (
    SNAPSHOT_DTTM TIMESTAMP_NTZ,
    FACILITY STRING,
    MODALITY STRING,
    ORDERS_WAITING NUMBER,
    MEDIAN_TAT_MINS NUMBER,
    P90_TAT_MINS NUMBER,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
