-- MRN chart-review semantic-view query templates.
-- Bind :mrn in secure runtime only. Do not log PHI identifiers or returned note text externally.

USE DATABASE DB_TEAM_STOLLERY_AND_ALBERTA_CHILDRENS_HOSPITAL_ANALYTICS;
USE SCHEMA MSB_CLINICAL_GENETICS;
USE WAREHOUSE WH_SMALL;

SELECT DEPARTMENT_NAME, FULL_NOTE, NOTE_ID, PAT_MRN_ID, NOTE_CSN_ID, CONTACT_DATE, ENT_INST_LOCAL_DTTM, UPD_AUT_LOCAL_DTTM
FROM SV_ADMISSION_HP_NOTES
WHERE PAT_MRN_ID = :mrn
ORDER BY UPD_AUT_LOCAL_DTTM DESC;

SELECT DEPARTMENT_NAME, NAME, NOTE_ID, NOTE_TEXT, PAT_MRN_ID, LINE, NOTE_CSN_ID, CONTACT_DATE, ENT_INST_LOCAL_DTTM, UPD_AUT_LOCAL_DTTM
FROM SV_CONSULT_NOTES
WHERE PAT_MRN_ID = :mrn
ORDER BY UPD_AUT_LOCAL_DTTM DESC;

SELECT AUTHRZING_PROV_ID, BILLING_PROV_ID, DESCRIPTION, NARRATIVE, ORDER_PROC_ID, PAT_ENC_CSN_ID, PAT_ID, PAT_MRN_ID, PROC_ID, RESULT_LAB_ID, ORDERING_DATE
FROM SV_IMAGING_NOTES
WHERE PAT_MRN_ID = :mrn
ORDER BY ORDERING_DATE DESC;

SELECT COMPONENT_ID, DESCRIPTION, NAME, ORDER_PROC_ID, PAT_ENC_CSN_ID, PAT_ID, PAT_MRN_ID, PROC_ID, RESULTS_COMP_CMT, RESULT_LAB_ID, ORDERING_DATE, ORDER_TIME, RESULT_TIME
FROM SV_LAB_REPORTS
WHERE PAT_MRN_ID = :mrn
ORDER BY RESULT_TIME DESC;

SELECT PAT_MRN_ID, DEPARTMENT_NAME, IP_NOTE_TYPE_C, NOTE_CSN_ID, NOTE_ID, NOTE_TEXT, CONTACT_DATE, ENT_INST_LOCAL_DTTM, UPD_AUT_LOCAL_DTTM
FROM SV_ENC_NOTES
WHERE PAT_MRN_ID = :mrn
ORDER BY UPD_AUT_LOCAL_DTTM DESC;

SELECT DESCRIPTION, DX_NAME, PAT_ID, PAT_MRN_ID, PROBLEM_CMT, PROBLEM_STATUS, NOTED_DATE, RESOLVED_DATE
FROM SV_PROBLEM_LIST
WHERE PAT_MRN_ID = :mrn
ORDER BY NOTED_DATE DESC;

SELECT COMMENTS, DX_NAME, PAT_ENC_CSN_ID, PAT_ID, PAT_MRN_ID, CONTACT_DATE
FROM SV_MEDICAL_HISTORY
WHERE PAT_MRN_ID = :mrn
ORDER BY CONTACT_DATE DESC;

SELECT DEPARTMENT_NAME, DX_NAME, NOTE_CSN_ID, NOTE_ID, NOTE_TEXT, PAT_ENC_CSN_ID, PAT_MRN_ID, CONTACT_DATE, ENT_INST_LOCAL_DTTM, UPD_AUT_LOCAL_DTTM
FROM SV_EDPROVIDER_NOTES
WHERE PAT_MRN_ID = :mrn
ORDER BY UPD_AUT_LOCAL_DTTM DESC;

SELECT DEPARTMENT_NAME, PAT_ID, PAT_MRN_ID, PCP_PROV_ID, PROV_NAME, PROV_TYPE, REASON_FOR_REFERRAL, REFD_BY_DEPT_ID, REFD_TO_DEPT_ID, REFERRAL_CLASS, REFERRAL_ID, REFERRAL_PROV_ID, REFERRAL_STATUS, REFERRAL_TYPE, REFERRING_DEPARTMENT, REFERRING_PROV_ID, SCHED_STATUS, ENTRY_DATE, EXP_DATE, SERV_DATE, START_DATE
FROM SV_REFERRALS
WHERE PAT_MRN_ID = :mrn
ORDER BY ENTRY_DATE DESC;
