-- Simulation-ready feature tables and outputs.
-- These are intended for governed internal pilots after validation.

CREATE SCHEMA IF NOT EXISTS SIMULATION;

CREATE OR REPLACE TABLE SIMULATION.BASELINE_STAGE_DISTRIBUTIONS AS
SELECT
  INSTITUTION_NAME,
  TRIAGE_LEVEL,
  PATIENT_AGE_GROUP,
  PRESENTING_COMPLAINT,
  APPROX_PERCENTILE(FIRST_CONTACT_TO_TRIAGE_HRS, 0.50) AS TRIAGE_P50_HRS,
  APPROX_PERCENTILE(FIRST_CONTACT_TO_TRIAGE_HRS, 0.90) AS TRIAGE_P90_HRS,
  APPROX_PERCENTILE(FIRST_CONTACT_TO_ROOMED_HRS, 0.50) AS ROOMED_P50_HRS,
  APPROX_PERCENTILE(FIRST_CONTACT_TO_ROOMED_HRS, 0.90) AS ROOMED_P90_HRS,
  APPROX_PERCENTILE(FIRST_CONTACT_TO_PIA_HRS, 0.50) AS PIA_P50_HRS,
  APPROX_PERCENTILE(FIRST_CONTACT_TO_PIA_HRS, 0.90) AS PIA_P90_HRS,
  APPROX_PERCENTILE(PIA_TO_DISPOSITION_HRS, 0.50) AS TREATMENT_P50_HRS,
  APPROX_PERCENTILE(PIA_TO_DISPOSITION_HRS, 0.90) AS TREATMENT_P90_HRS,
  APPROX_PERCENTILE(BOARDING_HRS, 0.50) AS BOARDING_P50_HRS,
  APPROX_PERCENTILE(BOARDING_HRS, 0.90) AS BOARDING_P90_HRS,
  COUNT(*) AS VISITS
FROM CURATED.V_ED_VISIT_STAGE_DURATIONS
GROUP BY 1,2,3,4;

CREATE OR REPLACE TABLE SIMULATION.SCENARIO_AUDIT_OUTPUTS (
  SCENARIO_ID STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FACILITY STRING,
  HORIZON_HOURS NUMBER,
  REPLICATIONS NUMBER,
  RANDOM_SEED NUMBER,
  INPUT_JSON VARIANT,
  SUMMARY_JSON VARIANT,
  BOTTLENECK_JSON VARIANT,
  UTILIZATION_JSON VARIANT,
  HUMAN_REVIEW_REQUIRED BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE VIEW SIMULATION.V_OBSERVED_STAGE_CONCURRENCY AS
SELECT
  INSTITUTION_NAME,
  DATE_TRUNC('hour', FIRST_CONTACT_DATETIME) AS OBSERVED_HOUR,
  COUNT_IF(TRIAGE_DATETIME IS NOT NULL AND TRIAGE_DATETIME >= FIRST_CONTACT_DATETIME) AS TRIAGE_INTERVAL_COUNT,
  COUNT_IF(INITIAL_ROOMED_IN_DATETIME IS NOT NULL AND PHYSICIAN_INITIAL_ASSESSMENT_DATETIME IS NOT NULL) AS ROOMED_TO_PIA_INTERVAL_COUNT,
  COUNT_IF(DECISION_TO_ADMIT_DATETIME IS NOT NULL AND LAST_CONTACT_DATETIME IS NOT NULL) AS BOARDING_INTERVAL_COUNT
FROM CURATED.V_ED_VISITS_CORE
GROUP BY 1,2;
