-- Feature views derived only from TB_ED_VISITS-contracted fields.

CREATE OR REPLACE VIEW CURATED.V_ED_VISIT_STAGE_DURATIONS AS
SELECT
  DATA_RECORD_ID,
  INSTITUTION_NAME,
  INSTITUTION_ZONE_NAME,
  TRIAGE_LEVEL,
  PATIENT_AGE_GROUP,
  PRESENTING_COMPLAINT,
  DATEDIFF('minute', FIRST_CONTACT_DATETIME, TRIAGE_DATETIME) / 60.0 AS FIRST_CONTACT_TO_TRIAGE_HRS,
  DATEDIFF('minute', FIRST_CONTACT_DATETIME, INITIAL_ROOMED_IN_DATETIME) / 60.0 AS FIRST_CONTACT_TO_ROOMED_HRS,
  DATEDIFF('minute', FIRST_CONTACT_DATETIME, PHYSICIAN_INITIAL_ASSESSMENT_DATETIME) / 60.0 AS FIRST_CONTACT_TO_PIA_HRS,
  DATEDIFF('minute', PHYSICIAN_INITIAL_ASSESSMENT_DATETIME, DISPOSITION_DATETIME) / 60.0 AS PIA_TO_DISPOSITION_HRS,
  ED_LOS_DECISION_TO_ADMIT_TO_LAST_CONTACT_HRS AS BOARDING_HRS,
  ED_LOS_HRS
FROM CURATED.V_ED_VISITS_CORE;

CREATE OR REPLACE VIEW CURATED.V_ED_ARRIVAL_PATTERNS AS
SELECT
  INSTITUTION_NAME,
  INSTITUTION_ZONE_NAME,
  DAYOFWEEK(FIRST_CONTACT_DATETIME) AS ARRIVAL_DAY_OF_WEEK,
  HOUR(FIRST_CONTACT_DATETIME) AS ARRIVAL_HOUR,
  TRIAGE_LEVEL,
  PATIENT_AGE_GROUP,
  PRESENTING_COMPLAINT,
  ARRIVAL_MODE,
  COUNT(*) AS ARRIVALS
FROM CURATED.V_ED_VISITS_CORE
GROUP BY 1,2,3,4,5,6,7,8;

CREATE OR REPLACE VIEW CURATED.V_ED_ROUTE_PROBABILITIES AS
SELECT
  INSTITUTION_NAME,
  TRIAGE_LEVEL,
  PATIENT_AGE_GROUP,
  PRESENTING_COMPLAINT,
  DISPOSITION_PERFORMANCE_REPORT,
  COUNT(*) AS VISITS,
  RATIO_TO_REPORT(COUNT(*)) OVER (
    PARTITION BY INSTITUTION_NAME, TRIAGE_LEVEL, PATIENT_AGE_GROUP, PRESENTING_COMPLAINT
  ) AS ROUTE_PROBABILITY
FROM CURATED.V_ED_VISITS_CORE
GROUP BY 1,2,3,4,5;
