-- Hybrid view joining constrained ED visit features to public/open contextual features.
-- This view should not expose direct patient identifiers.

CREATE OR REPLACE VIEW ANALYTICS.V_ED_VISITS_WITH_OPEN_CONTEXT AS
SELECT
  v.DATA_RECORD_ID,
  v.INSTITUTION_NAME,
  v.INSTITUTION_ZONE_NAME,
  v.DEPARTMENT_TYPE,
  v.TRIAGE_LEVEL,
  v.PATIENT_AGE_GROUP,
  v.PRESENTING_COMPLAINT,
  v.ARRIVAL_MODE,
  v.DISPOSITION_PERFORMANCE_REPORT,
  v.FIRST_CONTACT_DATETIME,
  v.ED_LOS_HRS,
  v.ED_LOS_DECISION_TO_ADMIT_TO_LAST_CONTACT_HRS,
  w.ESTIMATED_WAIT_MINS AS PUBLIC_WAIT_MINS_NEAREST_HOUR,
  e.AQHI,
  e.WILDFIRE_SMOKE_RISK,
  e.WEATHER_ALERT_COUNT,
  e.ENVIRONMENTAL_STRESS_INDEX,
  t.TRAVEL_FRICTION_INDEX,
  r.PEDIATRIC_PRESSURE_INDEX,
  'HYBRID_OPEN_INTERNAL_READY' AS LINEAGE_CATEGORY
FROM CURATED.V_ED_VISITS_CORE v
LEFT JOIN OPEN_DATA.AHS_ED_WAIT_TIMES w
  ON w.FACILITY = v.INSTITUTION_NAME
 AND DATE_TRUNC('hour', w.POSTED_TIMESTAMP) = DATE_TRUNC('hour', v.FIRST_CONTACT_DATETIME)
LEFT JOIN OPEN_DATA.ENVIRONMENTAL_STRESS e
  ON e.FACILITY = v.INSTITUTION_NAME
 AND DATE_TRUNC('hour', e.OBSERVED_AT) = DATE_TRUNC('hour', v.FIRST_CONTACT_DATETIME)
LEFT JOIN OPEN_DATA.TRAVEL_FRICTION t
  ON t.FACILITY = v.INSTITUTION_NAME
 AND DATE_TRUNC('hour', t.OBSERVED_AT) = DATE_TRUNC('hour', v.FIRST_CONTACT_DATETIME)
LEFT JOIN OPEN_DATA.AB_RESPIRATORY_SURVEILLANCE r
  ON r.ZONE = v.INSTITUTION_ZONE_NAME
 AND r.WEEK_START = DATE_TRUNC('week', v.FIRST_CONTACT_DATETIME);
